apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: X_PROJECT-drone
  namespace: default
spec:
  secretName: X_PROJECT-drone-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: X_SERVER_HOST
  dnsNames:
  - X_SERVER_HOST
  acme:
    config:
    - http01:
        ingress: X_PROJECT-drone
      domains:
      - X_SERVER_HOST
